### PR TITLE
Django Middleware -> Get raw data properly, currently fails when empty

### PR DESCRIPTION
**Pull request by ckcollab**
Hopeful fix for this error:

`AttributeError: 'WSGIRequest' object has no attribute 'raw_post_data'`

### CODE REVIEW

**Comment by fundead** [comment]
Thanks for your work on this PR, this is a valuable one to tidy up. Raygun4py is next in line for a provider refresh and I'll be sure to get this merged in and sort out those failing tests (something in the code coverage, hm) in the next release which should be in the near term.

Regards,

Callum Gavin
Raygun Limited

**Comment by ckcollab** [comment]
Woo! Thanks :)

**Comment by vosi** [comment]
so when yo uwill merge it ?
this issue hits me too

**Comment by fundead** [comment]
This provider is scheduled for a review next, which will result in this PR being merged following QA and unit testing/integration testing.

**Comment by diwu1989** [comment]
I need this one too

**Comment by fundead** [comment]
This issue is now resolved in the latest release above which will be uploaded to pypi shortly.

**Comment by ckcollab** [comment]
Thanks boys!

**Pull request closed without merging**
